name: Build and Release Firmware

permissions:
  contents: write

on:
    push:
      tags:
        - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: nowsprinting/check-version-format-action@v3
      id: version
      with:
        prefix: 'v'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build firmware
      run: platformio run

    - name: Rename firmware
      run: mv .pio/build/wt32-eth01/firmware.bin wt32-eth0.bin

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: ${{ steps.version.outputs.prerelease != '' }}
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: |
          wt32-eth0.bin
